# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'sigabrtProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sigabrtProject
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Storage'
pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare'
pod 'TextFieldEffects'
pod 'Nuke', '~> 5.0'
pod 'UITextField+Shake', '~> 1.1'

end
